### ISSUE TITLE
bug battery

### ISSUE THREAD

**Issue by Kato4imoto** [miuihu/android_kernel_xiaomi_armor#1]
Hi. The kernel is launched on miu 6 without problems, but there is a problem with the battery, the charge gives out 0% and isn't charged, the path /sys/class/power_supply/ folder "battery" not found. what to do?

**Comment by balika011** [comment]
Wierd. ATM I don't own any 1S, so i can't test the code on a real device. Can you try the 66982fb one?

**Comment by Kato4imoto** [comment]
I already downloaded this code, also the problem remained.

**Comment by balika011** [comment]
66982fb is a tested code. It was working well on my 1S.

**Comment by balika011** [comment]
Can you try this file: http://ota.miui.hu/craps/boot.img ?

**Comment by Kato4imoto** [comment]
http://snag.gy/4yfsg.jpg
now I try..

**Comment by balika011** [comment]
can you upload the dmesg somewhere?

**Comment by Kato4imoto** [comment]
Your boot works and the battery OK.
http://pastebin.com/96NzTjmB - my boot

**Comment by balika011** [comment]
I used the same source as pub. Wierd.

**Comment by Kato4imoto** [comment]
Weird. Tell, please, what compiler at you? Share the link, please.

**Comment by Kato4imoto** [comment]
Ooo!!! Your boot, I replaced the file zImage - works!!!
Thanks!
