### ISSUE TITLE
ft5x06 buggy dt2w

### ISSUE THREAD

**Issue by Kato4imoto** [miuihu/android_kernel_xiaomi_armor#2]
Please watch the video https://www.youtube.com/watch?v=GDyuaB-oDOI

**Comment by thewisenerd** [comment]
i know fix and will be sending in pull request later if okay with @balika011 can merge in.

**Comment by eloimuns** [comment]
It's bit buggy too @thewisenerd, long press and later a fast press detects as good. 

I think that dt2w need to be 2 fast press.

**Comment by balika011** [comment]
This kernel contains an old, unfinished ft5036 driver. I was working on a hardware solution for dt2w, that I haven't published.

**Comment by eloimuns** [comment]
@balika011 And the question is: When you will update with this solution? :D

**Comment by balika011** [comment]
Without 1s? Sorry, but I can't.

**Comment by Kato4imoto** [comment]
if to take the driver from 4.3, it will work or not?

**Comment by balika011** [comment]
Fixed.

**Comment by thewisenerd** [comment]
how does removing doubletap2wake reason as fixing the issue?

or do you have a better solution coming along?

**Comment by balika011** [comment]
Better to have a no feature then a buggy feature, isn't it? I still don't own a Redmi 1S. The code, what i update is tested on a Redmi 2. Some drivers are the same in these devices. (For ex.: Mi2A, Rm1S RmN4G, Rm2, RmND4G has the same bq2022 chip in the battery. Rm2 has the battery size and pinout as Rm1S. If you add the BM44 devtree to this kernel, you can use a Rm2 battery in your Rm1S and vice versa.)

**Comment by thewisenerd** [comment]
but I said I had a fix for this ready.

**Comment by Kato4imoto** [comment]
I updated the driver, touch doesn't work for redmi 1s(

**Comment by Kato4imoto** [comment]
than you can repack dtb?
