### ISSUE TITLE
touch works opposite

### ISSUE THREAD

**Issue by ghost** [miuihu/android_kernel_xiaomi_armor#4]
balika i think touch is little messed up...the touch works in opposite direction, top touch works as bottom and bottom works as top and also back menu home key goes up
same with right and left

**Comment by balika011** [comment]
Please install the stock kernel end test if you have the same issue.

**Comment by ghost** [comment]
i was on stock only before...

edit : somehow revert back to stock but problem remains, install the rom again still problem remains,
now i fucked up...going to install fastboot rom and see how thing goes

edit2 : totally fucked up...tried everything, flash fasboot rom with full format still touch the same
anyway to get back things normal @balika011 ?

**Comment by balika011** [comment]
Then you broken your touchscreen chip whit a wrong firmware, and we don't have a stock one. Congrats.

**Comment by ghost** [comment]
fuck!! any way to get things back...cant we edit this one

**Comment by balika011** [comment]
Give it back to xiaomi and they will fix it for you.

**Comment by ghost** [comment]
that's the only reason i am asking from you...there is no Xiaomi Service Center in my City

**Comment by balika011** [comment]
You can filp it in driver code, but you'll have to use modified kernel on every rom.

**Comment by ghost** [comment]
yeah that will be fine....send you email
can we talk there??

**Comment by balika011** [comment]
Write on me in hangouts.

**Comment by eloimuns** [comment]
You will need to build a kernel jump. If yoi need help i can.

**Comment by ghost** [comment]
that will be great @eloimuns...can we talk on hangout
here's my email beastdragon01@gmail.com
